export default Recipes = [
  {
    recipeId: "1",
    recipeName: "Chicken",
    recipeDescription:
      "Tuna Tartare is a good cooking type that 'll give you all you need.Tuna Tartare is a good cooking type that 'll give you all you need.Tuna Tartare is a good cooking type that 'll give you all you need.",
    recipeImage: require("../../assets/images/poulet-assiette.png"),
    cookTime: "40mins",
    rating: "1.2",
    RecipeIngredians: [
      { id: "1", nom: "salt" },
      { id: "2", nom: "water" },
      { id: "3", nom: "bread" },
      { id: "4", nom: "caroot" },
      { id: "5", nom: "Sugar" },
    ],
    RecipeSteps: [
      { id: "1", nom: "make your work space clean" },
      { id: "2", nom: "wash your hands" },
      { id: "3", nom: "cut your bread" },
      { id: "4", nom: "make fire" },
      { id: "5", nom: "smile" },
    ],
  },
  {
    recipeId: "2",
    recipeName: "coffee",
    recipeDescription:
      "Tuna Tartare is a good cooking type that 'll give you all you need.Tuna Tartare is a good cooking type that 'll give you all you need.Tuna Tartare is a good cooking type that 'll give you all you need.",
    recipeImage: require("../../assets/images/delicieuse-collation.png"),
    cookTime: "15mins",
    rating: "4.5",
    RecipeIngredians: [
      { id: "1", nom: "salt" },
      { id: "2", nom: "water" },
      { id: "3", nom: "bread" },
      { id: "4", nom: "caroot" },
      { id: "5", nom: "Sugar" },
    ],
    RecipeSteps: [
      { id: "1", nom: "make your work space clean" },
      { id: "2", nom: "wash your hands" },
      { id: "3", nom: "cut your bread" },
      { id: "4", nom: "make fire" },
      { id: "5", nom: "smile" },
    ],
  },
  {
    recipeId: "3",
    recipeName: "Lil sandwich",
    recipeDescription:
      "Tuna Tartare is a good cooking type that 'll give you all you need.Tuna Tartare is a good cooking type that 'll give you all you need.Tuna Tartare is a good cooking type that 'll give you all you need.",
    recipeImage: require("../../assets/images/delicieux-sandwichs.png"),
    cookTime: "40mins",
    rating: "1.2",
    RecipeIngredians: [
      { id: "1", nom: "salt" },
      { id: "2", nom: "water" },
      { id: "3", nom: "bread" },
      { id: "4", nom: "caroot" },
      { id: "5", nom: "Sugar" },
    ],
    RecipeSteps: [
      { id: "1", nom: "make your work space clean" },
      { id: "2", nom: "wash your hands" },
      { id: "3", nom: "cut your bread" },
      { id: "4", nom: "make fire" },
      { id: "5", nom: "smile" },
    ],
  },
  {
    recipeId: "4",
    recipeName: "Big Sandwichs",
    recipeDescription:
      "Tuna Tartare is a good cooking type that 'll give you all you need.Tuna Tartare is a good cooking type that 'll give you all you need.Tuna Tartare is a good cooking type that 'll give you all you need.",
    recipeImage: require("../../assets/images/gros-sandwich.png"),
    cookTime: "20mins",
    rating: "3.2",
    RecipeIngredians: [
      { id: "1", nom: "salt" },
      { id: "2", nom: "water" },
      { id: "3", nom: "bread" },
      { id: "4", nom: "caroot" },
      { id: "5", nom: "Sugar" },
    ],
    RecipeSteps: [
      { id: "1", nom: "make your work space clean" },
      { id: "2", nom: "wash your hands" },
      { id: "3", nom: "cut your bread" },
      { id: "4", nom: "make fire" },
      { id: "5", nom: "smile" },
    ],
  },
  {
    recipeId: "5",
    recipeName: "Halloween Burger",
    recipeDescription:
      "Tuna Tartare is a good cooking type that 'll give you all you need.Tuna Tartare is a good cooking type that 'll give you all you need.Tuna Tartare is a good cooking type that 'll give you all you need.",
    recipeImage: require("../../assets/images/halloween-burger.png"),
    cookTime: "12mins",
    rating: "4.2",
    RecipeIngredians: [
      { id: "1", nom: "salt" },
      { id: "2", nom: "water" },
      { id: "3", nom: "bread" },
      { id: "4", nom: "caroot" },
      { id: "5", nom: "Sugar" },
    ],
    RecipeSteps: [
      { id: "1", nom: "make your work space clean" },
      { id: "2", nom: "wash your hands" },
      { id: "3", nom: "cut your bread" },
      { id: "4", nom: "make fire" },
      { id: "5", nom: "smile" },
    ],
  },
  {
    recipeId: "6",
    recipeName: "Moka Glace",
    recipeDescription:
      "Tuna Tartare is a good cooking type that 'll give you all you need.Tuna Tartare is a good cooking type that 'll give you all you need.Tuna Tartare is a good cooking type that 'll give you all you need.",
    recipeImage: require("../../assets/images/moka-glace1.avif"),
    cookTime: "10mins",
    rating: "2.2",
    RecipeIngredians: [
      { id: "1", nom: "salt" },
      { id: "2", nom: "water" },
      { id: "3", nom: "bread" },
      { id: "4", nom: "caroot" },
      { id: "5", nom: "Sugar" },
    ],
    RecipeSteps: [
      { id: "1", nom: "make your work space clean" },
      { id: "2", nom: "wash your hands" },
      { id: "3", nom: "cut your bread" },
      { id: "4", nom: "make fire" },
      { id: "5", nom: "smile" },
    ],
  },
  {
    recipeId: "7",
    recipeName: "Spice Chicken",
    recipeDescription:
      "Tuna Tartare is a good cooking type that 'll give you all you need.Tuna Tartare is a good cooking type that 'll give you all you need.Tuna Tartare is a good cooking type that 'll give you all you need.",
    recipeImage: require("../../assets/images/poulet-assiette.png"),
    cookTime: "30mins",
    rating: "4.2",
    RecipeIngredians: [
      { id: "1", nom: "salt" },
      { id: "2", nom: "water" },
      { id: "3", nom: "bread" },
      { id: "4", nom: "caroot" },
      { id: "5", nom: "Sugar" },
    ],
    RecipeSteps: [
      { id: "1", nom: "make your work space clean" },
      { id: "2", nom: "wash your hands" },
      { id: "3", nom: "cut your bread" },
      { id: "4", nom: "make fire" },
      { id: "5", nom: "smile" },
    ],
  },
  {
    recipeId: "8",
    recipeName: "Barbecue Chicken",
    recipeDescription:
      "Tuna Tartare is a good cooking type that 'll give you all you need.Tuna Tartare is a good cooking type that 'll give you all you need.Tuna Tartare is a good cooking type that 'll give you all you need.",
    recipeImage: require("../../assets/images/poulet-barbecue.png"),
    cookTime: "35mins",
    rating: "4",
    RecipeIngredians: [
      { id: "1", nom: "salt" },
      { id: "2", nom: "water" },
      { id: "3", nom: "bread" },
      { id: "4", nom: "caroot" },
      { id: "5", nom: "Sugar" },
    ],
    RecipeSteps: [
      { id: "1", nom: "make your work space clean" },
      { id: "2", nom: "wash your hands" },
      { id: "3", nom: "cut your bread" },
      { id: "4", nom: "make fire" },
      { id: "5", nom: "smile" },
    ],
  },
  {
    recipeId: "9",
    recipeName: "Poulet Grille",
    recipeDescription:
      "Tuna Tartare is a good cooking type that 'll give you all you need.Tuna Tartare is a good cooking type that 'll give you all you need.Tuna Tartare is a good cooking type that 'll give you all you need.",
    recipeImage: require("../../assets/images/poulet-grille.png"),
    cookTime: "1h20mins",
    rating: "3.2",
    RecipeIngredians: [
      { id: "1", nom: "salt" },
      { id: "2", nom: "water" },
      { id: "3", nom: "bread" },
      { id: "4", nom: "caroot" },
      { id: "5", nom: "Sugar" },
    ],
    RecipeSteps: [
      { id: "1", nom: "make your work space clean" },
      { id: "2", nom: "wash your hands" },
      { id: "3", nom: "cut your bread" },
      { id: "4", nom: "make fire" },
      { id: "5", nom: "smile" },
    ],
  },
  {
    recipeId: "10",
    recipeName: "Vegan Dishe",
    recipeDescription:
      "Tuna Tartare is a good cooking type that 'll give you all you need.Tuna Tartare is a good cooking type that 'll give you all you need.Tuna Tartare is a good cooking type that 'll give you all you need.",
    recipeImage: require("../../assets/images/restaurant.png"),
    cookTime: "40mins",
    rating: "3.2",
    RecipeIngredians: [
      { id: "1", nom: "salt" },
      { id: "2", nom: "water" },
      { id: "3", nom: "bread" },
      { id: "4", nom: "caroot" },
      { id: "5", nom: "Sugar" },
    ],
    RecipeSteps: [
      { id: "1", nom: "make your work space clean" },
      { id: "2", nom: "wash your hands" },
      { id: "3", nom: "cut your bread" },
      { id: "4", nom: "make fire" },
      { id: "5", nom: "smile" },
    ],
  },
  {
    recipeId: "11",
    recipeName: "Brasilian Spagettis",
    recipeDescription:
      "Tuna Tartare is a good cooking type that 'll give you all you need.Tuna Tartare is a good cooking type that 'll give you all you need.Tuna Tartare is a good cooking type that 'll give you all you need.",
    recipeImage: require("../../assets/images/spaghettis-boulette.png"),
    cookTime: "30mins",
    rating: "4.2",
    RecipeIngredians: [
      { id: "1", nom: "salt" },
      { id: "2", nom: "water" },
      { id: "3", nom: "bread" },
      { id: "4", nom: "caroot" },
      { id: "5", nom: "Sugar" },
    ],
    RecipeSteps: [
      { id: "1", nom: "make your work space clean" },
      { id: "2", nom: "wash your hands" },
      { id: "3", nom: "cut your bread" },
      { id: "4", nom: "make fire" },
      { id: "5", nom: "smile" },
    ],
  },
];
